export type Entry = {
  ampURL: string;
  articleID: number;
  author: string;
  clickTrackingLink: string;
  highlight: boolean;
  highlightType: string;
  link: string;
  mobileLink: string;
  mobileShareURL: string;
  orderNo: number;
  originalMobileUrl: string;
  originalPicture: string;
  originalURL: string;
  picture: string;
  publishedDate: string;
  publishedDateJS: string;
  sectionID: number;
  shareURL: string;
  shortDescription: string;
  sourceID: number;
  timeSince: string;
  title: string;
};
